# Site settings
title: "Jonathan Nafziger's Resume"
description: "A resume for Jonathan Nafziger"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
#  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jonathan Nafziger"
resume_title:                   "Programmer, Physicist, Problem Solver"
resume_contact_email:           "jnafziger@gmail.com"
resume_contact_telephone:       "765-430-8354"
resume_contact_address:         "902 North Clarkdale, Muncie, IN"
resume_header_contact_info: "902 North Clarkdale, Muncie, IN | 765-430-8354 | jnafziger@gmail.com"
resume_header_intro: "<p>Physics PhD with a passion for solving problems, playing with software, and learning new things</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_papers:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jnafzig/"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jonathan-nafziger/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://jnafzig.github.io"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
